#Nom de l'application
spring.application.name=info-asso-api

#URL de la base de données
spring.datasource.url=jdbc:mysql://localhost:3306/info_asso_db?useSSL=false&serverTimeZone=UTC
spring.datasource.username=root
spring.datasource.password=rootroot

#Strategie de mise à jour de la bdd
spring.jpa.hibernate.ddl-auto=update

#Afficher les requêtes SQL dans la console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
