#Nom de l'application
spring.application.name=info-asso-api


server.port=8080

#URL de la base de donnees
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#Strategie de mise a jour de la bdd
spring.jpa.hibernate.ddl-auto=update

#Afficher les requetes SQL dans la console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#A MODIFIER AVEC VARIABLE ENV
infoasso.app.jwtSecret=${JWT_SECRET}
infoasso.app.jwtExpirationMs=${JWT_EXPIRATION}